@Restaurants.API_HostAddress = https://localhost:7046
@id=10


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "Test",
  "description": "Demo Restaurant",
  "hasDelivery": true,
  "contactEmail": "contact@pizzatown.com",
  "contactNumber": "01234567890",
  "city": "Cairo",
  "street": "El-Tahrir Street",
  "postalCode": "11511"
}




###


PUT {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json

{
  "name": "Demo - Updated",
  "description": "Demo Demo - Updated",
  "hasDelivery": true,
  "contactEmail": "contactDemo@pizzatown.com",
  "contactNumber": "01234567810",
  "city": "Dameitta11",
  "street": "El-Tahrir Street - Updated",
  "postalCode": "11223"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###
