@Restaurants.API_HostAddress = https://localhost:7046
@restaurantId=1
@id=1

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer CfDJ8BWCGbbWCbJNsiZSUm7bQlSbZ19c-uNGQMqQJh9mxPaerIOjQvzCEMU_fha6ZF80vXSGkSNCmOnVNiaJKFpZHOfK2VeWGqgE5Xr3P98itmbXNqReKAEAwmD2Y5F_jUqb4jYUMzhjeHW14Zq-d5W0_HhHq80wp9T3ptkr2x-3U3OxJZS3whGzlZZU2YApBjM8zrS-rzY2TaTCxGtU69mrvwpLwKX05SKIAgrsDAZc4p41t2QTTjFmk_3gNQL1NY2CCR1Q906Eh-7hU8bO1IT_I9rXiTMmabCMGRDCgvBFahX5QWL6z9N7ib1fJERF3AnKYm7qWuwlzpiZqHi5LMr41O70l3HIMcVnmgTmsDxhW2yowx_pmw7B5oyB9svTanGa4vpd1Fg0yxaU3E659NRt3FDjnJbzIq8bSqEC1pvQdKXI13x8yjEOrt69Vk35x3w-XMZQOnDzXTOWmWsMJcFGYiyCfxHZbRu9rIZRDnzcktoTrX7j5fpwlWy7s5g4jJUP7DXoALfw0XG9g455GUTsZP0ICC1nxj_5LDgbMQTB95-3FXH5a5yd181BcCjqYp_HZ_DbcA2AUiw8aH0ssN_dhKE3IFLItiSUv95gckZMvkIMzpQGyxuvIRT9GhxzzBHUaJYhfkPPa7ikeA4uu7sLdwMDaOnLrk-35UbVHKgUHbtj0abXJBBVQhb5hY2RBKBHP-0j69HjLmuXZeClsQ1YebDYfORMjGYbTdzwiZ7nccHBlBqKmOfllLmUh4bvZmbTZ4aft-ysUbnDic0hJ_80TV9Ngwt1YTXctl_g8CtMk8ZW8pVFVXHM1mBZjhcYM1_Pm7FtS3Yw9AvvRsJd4Pn8v_U

{
  "name": "Pizza Planet",
  "description": "Delicious wood-fired pizzas with customizable toppings.",
  "hasDelivery": true,
  "contactEmail": "order@pizzaplanet.com",
  "contactNumber": "01244556677",
  "city": "Port Said",
  "street": "22 Freedom Square",
  "postalCode": "42511"
}
###

PUT {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json

{
  //UpdateRestaurantCommand
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/categories

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type : application/json

{
  "email":"owner@gmail.com",
  "password":"Owner.Password12!"
}